### ISSUE TITLE
Armageddon's Blade campaigns aren't translated

### ISSUE THREAD

**Issue by Olegmods** [vcmi-mods/mega-pack-rus#9]
Reported from VK.

**Comment by GeorgeK1ng** [comment]
Seems like a lot of text is not translated in campaigns.json

**Comment by Olegmods** [comment]
> Seems like a lot of text is not translated in campaigns.json

Can you make translation for that file via HeroesLauncher's tool? After all, the localization here is kinda bad after all.

**Comment by GeorgeK1ng** [comment]
I have updated translation, note 2 campaigns are not translated. From my Czech translation I know both can be mapped from existing ones. You will see which one, it should be easy for native speaker. Just few words are changed in these non translated lines. So be carefull to keep correct story line. When you correctly map and full-fill campaings.json bump mod version aswell.

**Comment by Olegmods** [comment]
> I have updated translation, note 2 campaigns are not translated. From my Czech translation I know both can be mapped from existing ones. You will see which one, it should be easy for native speaker. Just few words are changed in these non translated lines. So be carefull to keep correct story line. When you correctly map and full-fill campaings.json bump mod version aswell.

Ok. Will look into it probably.
